### ISSUE TITLE
Persistent state size and growth rate

### ISSUE THREAD

**Issue by peterjgilbert** [oasisprotocol/oasis-core#1001]
Meta issue to track efforts to get state size and growth rate under control.

## Goal

Reduce the size of persistent state which includes our storage and Tendermint state.

## Linked issues
- [x] [Trim roothash blocks](https://github.com/oasislabs/ekiden/issues/986) - 1d
- [x] [Consider pruning old Tendermint application state](https://github.com/oasislabs/ekiden/issues/941) - 2d
- [x] [Trim redundant data in tags](https://github.com/oasislabs/ekiden/issues/1011) - 2d
- [x] [Disable the tendermint transaction indexer.](https://github.com/oasislabs/ekiden/issues/1029) - 0d
- [x] [Investigate compressing the tendermint databases.](https://github.com/oasislabs/ekiden/issues/1032) - 1d
- [x] [Investigate enabling compression for the k/v store.](https://github.com/oasislabs/ekiden/issues/1035)
- ~~~[Enforce storage expiration in the LevelDB backend (or use a backend that can expire storage)](https://github.com/oasislabs/ekiden/issues/1043)~~~
