### ISSUE TITLE
Merge dummy and compute nodes

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-core#1009]
Tracking issue for merging dummy and compute nodes.

## Goal

Currently there is a centralized dummy node that all the compute nodes talk to. There should only be a single Go-based node which encapsulates all functionality and operates in a distributed fashion. The existing Rust compute node should only be the worker implementation talking with the Go-based node over lightweight IPC.

## Linked issues
- [x] [Add centralized storage node subcommand](https://github.com/oasislabs/ekiden/issues/937) - 0.5d
- [x] [Tendermint validator committee](https://github.com/oasislabs/ekiden/issues/651) - 2d
- [x] [Port multilayer storage backend to Go](https://github.com/oasislabs/ekiden/issues/1008) - 3d
- [x] [Separate worker process from the compute node](https://github.com/oasislabs/ekiden/issues/673) - 8d
- [x] [Sandbox the worker process](https://github.com/oasislabs/ekiden/issues/104) - 1d
- [x] [Port worker host to Go](https://github.com/oasislabs/ekiden/issues/1179) - 2d
- [x] [Port roothash frontend to Go](https://github.com/oasislabs/ekiden/issues/1180) - 8d
- [x] [Allow roothash frontend to interrupt the worker](https://github.com/oasislabs/ekiden/issues/1010) - 4d
- [x] [Switch to using the merged Go node](https://github.com/oasislabs/ekiden/issues/1263)
- [x] [Cleanup Rust client backend arguments](https://github.com/oasislabs/ekiden/issues/1240) - 1d
- [x] [Each compute worker should register it's supported runtimes.](https://github.com/oasislabs/ekiden/issues/1126)
- [x] [Workers should support more than one runtime.](https://github.com/oasislabs/ekiden/issues/1125)
- [x] [ scheduler: Factor in runtime availability into scheduling.](https://github.com/oasislabs/ekiden/issues/1127)
- [x] [Emit underlying backend's block height in WatchBlocks](https://github.com/oasislabs/ekiden/issues/1247) - 1d
