### ISSUE TITLE
Staking and Economic Incentives

### ISSUE THREAD

**Issue by ryscheng** [oasisprotocol/oasis-core#101]
There should be a concept of stakes / bonds interacting in the system
* [ ] Compute nodes / miners should submit a bond when registering #310  / #204
* [ ] Registry should validate those #311 
* [ ] Consensus should resolve them #314 
* [ ] Punish nodes when things go wrong #102
* [ ] Testnet should run with ethereum nodes #580 / #581
