### ISSUE TITLE
Reduce dependencies among registry, roothash, and scheduler

### ISSUE THREAD

**Issue by pro-wh** [oasisprotocol/oasis-core#1097]
We've identified opportunities to reduce the dependencies among the registry, roothash, and scheduler systems. Let's do those, because it will prepare us for configuring the initial block from the registry, which may be useful for migration and special deployments.

## Details
Idea from #1041:

* [x] Move `Runtime` to registry (#1101)

Ideas from #1089:

* [x] Move some types to subpackages, such as `Block` (currently in roothash) (#1107)
* [x] Remove or relocate `Block`'s `Update` method (currently makes roothash depend on scheduler) (#1104)
* [x] Eliminate `Runtime` details from `Committee`, only the ID is used (currently makes scheduler depend on common) (#1112)

## Acceptance Criteria
* That we would be able to convey an initial `Block` from the registry system to the roothash system without encountering a dependency cycle.
* Type safety: breaking dependencies by erasing to `interface{}` or serialized `[]byte` is not acceptable.
