### ISSUE TITLE
Switch to using the merged Go node

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-core#1263]
After all parts of the merged Go node are done, we should switch to actually using the merged Go now.

This also includes changes to ops needed to deploy the new nodes.

#### Tasks
* [x] Change E2E tests to test the new Go compute worker, make sure everything works.
* [x] Update runtime-ethereum  E2E tests.
* [x] Update helm charts to deploy the new Go compute worker.
* [x] Remove old Ekiden compute node.
* [x] Update README to reflect the new Go node.
