### ISSUE TITLE
Proactive secure sharing key manager

### ISSUE THREAD

**Issue by bl4ck5un** [oasisprotocol/oasis-core#1346]
Implement and deploy the proactive secret sharing key management system.

RFC: https://github.com/oasislabs/rfcs/pull/49
Code repo: https://github.com/oasislabs/TigerTally

## Linked Issues

- [ ] [Herzberg's PSS](https://github.com/oasislabs/TigerTally/issues/1)
- [ ] [DKG](https://github.com/oasislabs/TigerTally/issues/2)
- [ ] [Polynomial ring Fq[x]](https://github.com/oasislabs/TigerTally/issues/3)
- [ ] [Naor's distributed PRF](https://github.com/oasislabs/TigerTally/issues/4)
- [ ] [Use SGX to protect shares](https://github.com/oasislabs/TigerTally/issues/5)
