### ISSUE TITLE
Replicated storage (FEC)

### ISSUE THREAD

**Issue by bennetyee** [oasisprotocol/oasis-core#1352]
Decentralized Storage epic issue for Oasis network Version E

## Goals

Permissionless open network with decentralized storage servers.  

## Details

Storage servers contract with the network to provide storage; network infra handles data migration at end of contract period.  Want greater storage efficiency (less data duplication); better fault tolerance efficiency.

## Linked Issues

* [ ] Switching to FEC+CAS instead of F+1 CAS for storage efficiency, higher sybil resistance
* [ ] Storage economics -- Gas fractions to pay compute vs storage, storage contract, slashing
* [ ] [Storage verification mechanism design](https://github.com/oasislabs/ekiden/issues/2007) -- what service performs probing to verify storage compliance, how to probe (uniform over all storage locations? over contracts? what frequency?)
* [ ] Storage server API changes (DoS prevention, authn/authz, storage receipt)
