### ISSUE TITLE
Stake service

### ISSUE THREAD

**Issue by bennetyee** [oasisprotocol/oasis-core#1353]
Tracking bug for a stake token contract/service.

## Goals

Build out infrastructure by which we get paid.

## Details

Participants in the Oasis network need to have stake tokens for a performance bond. Even for a closed chain, we need to have a mechanism by which authorized participants can buy stake to set up their servers.

We need to be able to sell stake tokens to compute resource owners who want to participate in the Oasis network. The stake token should be relatively stable in value: the users who write contracts / propose transactions must be able to quantify the adversarial cost to attack their computations, even though stake token holders should be able to trade their tokens on exchanges/markets such as coinbase.  This means that there should be a minimum price for the adversarial cost calculations, and we cannot arbitrarily sell coins and flood the market w/o affecting contract security; further, this may mean that we have to have some level of price support to dampen fluctuations, should compute resource sellers find better ROI with another network and sell our stake tokens.

## Linked Issues

 * [x] [Initial staking token backend design](https://github.com/oasislabs/private-rfcs/pull/82)
 * [ ] Stake pricing, price support (!) and/or price cap to ensure security/economic incentives/constraints are satisfied.
 * [ ] Stake slashing authorization -- which nodes can slash? How? (Committee scheduler gives consensus nodes the authorization?)
 * [ ] [Transaction fee schedule](https://github.com/oasislabs/ekiden/issues/1468)
 * [x] [Figure out stake migration](https://github.com/oasislabs/ekiden/issues/1472)
