### ISSUE TITLE
Security audit / Byzantifying

### ISSUE THREAD

**Issue by bennetyee** [oasisprotocol/oasis-core#1354]
## Goals

Make our MainNet secure and robust against attacks. Have capability for security monitoring, handling emergency zero-day code updates.

## Details

We need to secure our MainNet to be robust against Byzantine adversaries.  While we are not going to be an open, permissionless network in VerC, we will have users running transactions on our and our partners' servers, and we need to at least get security plans and testing infrastructure plans in place so that we will not design ourselves into corners for when we need to move to VerD.

## Linked Issues

* [ ] [Review cloud credential handling, bucket permissions, etc.  Plan for *annual* reviews.](https://github.com/oasislabs/ekiden/issues/1402)
* [ ] [Security monitoring.  IDS.  External security reports.  Continuous.](https://github.com/oasislabs/ekiden/issues/1403)
* [ ] Playbook for deciding whether to apply emergency patches, how to do releases, etc.  *Semi-annual* exercises.
* [ ] [External dependency monitoring. Get everybody to read https://research.swtch.com/deps.  Track up-stream fixes, CVEs, 0-day handling.](https://github.com/oasislabs/ekiden/issues/1405)
* [ ] [Inter-component interfaces -- test harnesses; fuzzing.](https://github.com/oasislabs/ekiden/issues/1406)
* [ ] Internal security review/audit
* [ ] External security review/audit
