### ISSUE TITLE
Storage Server API Design & Impl

### ISSUE THREAD

**Issue by bennetyee** [oasisprotocol/oasis-core#1357]
API design for CAS-based decentralized storage service

## Details

For VerC decentralized storage, we will have statically allocated/assigned storage committees onto which we store possibly-sharded data.  The [issue](https://github.com/oasislabs/ekiden/issues/925) and [current high-level design (and discussion) is here](https://docs.google.com/document/d/1KhOXxIfaxJvgo9V_UqTVBSfoZa8XcaBVZdrm8qiI0kY/edit?usp=sharing) but the basic CAS-based interfaces, whether we are implementing F+1 or FEC, should be essentially identical.

Lifetime of storage server is not limited by contract as in an open network, but we should have some facility to failover / clone state if/when a storage server must be decommissioned, or to reconstruct its storage from other replicas to ensure that the degree of fault tolerance does not degrade over time.

## Linked Issues

* [ ] [Specify a common merklized mutable key/value interface for runtimes](https://github.com/oasislabs/ekiden/issues/1383)
* [ ] [Storage root hash versioning](https://github.com/oasislabs/ekiden/issues/1378)
* [x] [Add receipts to storage interface](https://github.com/oasislabs/ekiden/issues/1384)
* [ ] gRPC interface for storage server
* [ ] Fast storage sync design for failover / clone state
* [ ] Throughput of XX txn/s
