### ISSUE TITLE
Pre-execution and read/write sets (Horizontal scaling)

### ISSUE THREAD

**Issue by bennetyee** [oasisprotocol/oasis-core#1375]
Horizontal scaling epic issue for version E of network

## Details

To increase throughput, we have a design for horizontally scaling our network to allow parallel execution of transactions.  This tracking issue collects the sub-issues and work that is needed to realize this.

## Linked Issues

Depends on epic #1576.
Depends on epic #1577.
Depends on epic oasislabs/runtime-ethereum#698.

* [ ] Specify interfaces needed for pre-execution nodes - 1w
* [ ] Runtime support for emitting per-transaction conflict sets - 1w
* [ ] Pre-execution nodes - 2w
* [ ] Transaction scheduler should use pre-execution information to schedule - 2w
* [ ] End-to-end performance optimization
* [ ] [Special case account balance handling to reduce conflicts](https://github.com/oasislabs/ekiden/issues/1466)
