### ISSUE TITLE
Economics (VerE)

### ISSUE THREAD

**Issue by bennetyee** [oasisprotocol/oasis-core#1392]
Tracking issue for longer term economics design.

## Goals

A well-designed market framework should be able to encourage resource providers to upgrade and/or increase the quantity of compute resources that works on the network as well as encourage smart contract users to run more code on the network.

## Details

The economics of the staking token and how we make gas available need to be worked out for the longer term.  Long term stake token price stability is important for adversarial cost factor computation, and gas is the ROI for buying and using stake to run network nodes.

Users will have to be able to buy gas to pay the service node operators (compute & storage nodes), and these operators will have to be able to convert the gas into USD to recognize as ROI.  The price of gas has to be recognized as fair to all parties.  Market efficiency is maximized when all parties can declare their true value for their participation: the break-even price for adding compute/storage resources to the network, for resource operators; and the break-even price for running possibly long term contracts for contract authors/transaction users.  Currently users must guess at the lowest-acceptable price that would get their transactions processed, which leads to either overpayment, or to waiting for proposed transactions to time out and submitting a new, higher gas-priced version, wasting time.

## Linked Issues

* [ ]  Economic design for stake pricing
* [ ]  Transaction / gas pricing economic design
* [ ]  Design / implementation of service for transaction proposers to buy gas (with stake?)
* [ ]  Design / implementation of market maker to set txn gas prices to increase txn demand
