### ISSUE TITLE
Continuous Security Monitoring, Audit Log Generation

### ISSUE THREAD

**Issue by bennetyee** [oasisprotocol/oasis-core#1403]
Continuous security monitoring.  IDS, Anomaly Detection, etc.  Audit logs.

## Details

We should have security monitoring / audits, so we can detect problems as they arise, and have enough secured audit logs so that a post-mortem can analyze what happened after the fact and figure out what to fix.

(Not sure if this should be an issue per se, since monitoring is continuous and testing of monitoring is quarterly.)

## Acceptance Criteria

* [ ] IDS/ADS installed, generates alerts.
* [ ] Periodic (quarterly?) testing of monitoring systems.
* [ ] Generation of access and other audit logs for production systems, retained for N months.
