### ISSUE TITLE
Intercomponent interface fuzzing harness

### ISSUE THREAD

**Issue by bennetyee** [oasisprotocol/oasis-core#1406]
Tracking epic issue for internal testability

## Goals

We need to have code testing/fuzzing mechanisms in place before we can efficiently do security audits beyond code inspection.

## Details

Implement fuzzing harness for interfaces between components.  Build mocks for dependent interfaces of the component under test.  Each test failure should turn into a unit test / regression test.

## Linked Issues
* [x] [Consensus interface](https://github.com/oasislabs/ekiden/issues/2245)
* [x] [Storage interface](https://github.com/oasislabs/ekiden/issues/2246)
* [ ] EnclaveRPC interface
* [ ] Transaction scheduler interface
* [ ] Compute P2P interface
* [ ] Merge P2P interface
* [ ] Worker-host interface
