### ISSUE TITLE
Improve storage performance

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-core#1413]
Tracking issue for improving storage performance across Ekiden Core and Ethereum Runtime.

## Goal

Understand bottlenecks of the current storage system in the context of runtime-ethereum (and wider) and work towards removing them to make common storage access patterns as fast as possible while keeping integrity guarantees.

## Linked Issues
* [ ] [Intermittent transaction failures on epoch transition](https://github.com/oasislabs/testnet-issues/issues/1)
* [x] [Profile the current storage hierarchy](https://github.com/oasislabs/ekiden/issues/1393)
* [x] [Storage hierarchy design doc](https://github.com/oasislabs/rfcs/issues/78)
* [x] [Fix tracing within the Go node](https://github.com/oasislabs/ekiden/issues/1389)
* [x] [Fix tracing into the Rust worker process](https://github.com/oasislabs/ekiden/issues/1474)
* [x] [Make tracing work across the whole compute committee](https://github.com/oasislabs/ekiden/issues/1475)
* [x] [Try different serializiation strategies for patricia trie](https://github.com/oasislabs/ekiden/issues/1163)
* [x] [Specify a common merklized mutable key/value interface for MKVS](https://github.com/oasislabs/ekiden/issues/1383)
* [x] [Investigate offloading maintenance of blockchain indices to gateway](https://github.com/oasislabs/runtime-ethereum/issues/576)
* [x] [Review state maintained by Parity-based runtime](https://github.com/oasislabs/runtime-ethereum/issues/575)
