### ISSUE TITLE
Transaction / gas pricing economic design

### ISSUE THREAD

**Issue by bennetyee** [oasisprotocol/oasis-core#1416]
Figure out how to price transactions.  Do we charge compute and storage gas components and price them separately?  Proposers / node operators declare their prices for each, in terms of stake?

## Details

In the Ethereum model that users are familiar with, gas is charged according to a fixed menu on a per-operation basis.  The transaction proposers specify the amount of either they are willing to pay for each unit of gas, and node operators can choose / prioritize proposed transactions based on the amount the proposers are willing to pay.

This is not optimally market efficient.

Proposers are motiviated to not declare their true break-even price for running the transaction, since they would prefer to pay less.  Node operators get a windfall when proposers are anxious to get their transactions committed quickly, but loses out on possible transaction volume due to proposers second guessing the least acceptable price and occasionally having to wait for transactions to time out of the pool.

Furthermore, we want to split gas into components for compute and storage (alkane and naphthane) to allow the resource pricing to change independently.  Having a market maker set a gas price based on supply and demand could work, but when there are two prices (vector) the market price determination is likely to be more complex.

## Acceptance Criteria

* [ ] Design exploration on market pricing for a single overall gas price.
* [ ] Design exploration on market pricing on a vector price (alkane and naphthane).
* [ ] Proposal for what to implement for VerD, VerE, etc, and how we evolve one to the other
