### ISSUE TITLE
Transaction Fee Schedule For Workers

### ISSUE THREAD

**Issue by bennetyee** [oasisprotocol/oasis-core#1468]
We need to establish mechanisms and a fee schedule to split up the gas earned from processing transactions among the compute committee nodes, storage committee nodes, root hash committee, etc, including a tax for common infrastructure (merkle tree maintenance, etc).

## Details

We need to design & implement mechanisms to (flexibly) have a fee schedule.  The EVM compute nodes have the gas fee schedule for EVM operations, and this could be similar; this could also be maintained as (read-mostly) data in a contract changes to which would be decided by vote by the community/foundation, though compiling in the fee schedule is more efficient.  Design decisions need to be made regarding:

- Which system component divies up the earned gas (compute committee, merge committee, ...)?  The compute committee already has to know about the account balance location in the merkle tree, but the merge committee decides whether a batch would be reverted due to data-dependency induced conflict set incompatibilities, and we need to decide whether (and how) such a batch would pay.  If the merge committee has to know this, then it will also have to know (more) about the structure of the merkle tree.

- What is a fair division for the gas earned?  This is a policy question and can be decided later, but the mechanisms for accounting for work done by various system entities (registry, committee scheduler, transaction scheduler, storage, merge, etc) has to be able to support the policy that we decide on.

## Linked Issues

* [ ] Design docs discussing the trade-offs of choices.  Implementation.
* [ ] [Runtime gas disbursement](https://github.com/oasislabs/ekiden/issues/2071)
* [ ] [Special case account balance handling to reduce conflicts](https://github.com/oasislabs/ekiden/issues/1466)
