### ISSUE TITLE
Storage interface and data structure v2

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-core#1513]
Tracking issue for implementing the new storage interface across Ekiden Core and Ethereum Runtime.

## Goal

Fully specify and implement the new storage interface that enables better caching, more control over how storage is done on all layers and easier evolution of the interface in the future.

## Linked Issues

* [x] [MKVS reference implementation](https://github.com/oasislabs/ekiden/pull/1505)
* [x] [Specify a common merklized mutable key/value interface for runtimes](https://github.com/oasislabs/ekiden/issues/1383) (update the storage interface RFC after initial exploration using a concrete data structure is done)
* [ ] [Specify protocol and data structure versioning for the MKVS interface(s)](https://github.com/oasislabs/ekiden/issues/1378)
* [x] [Rust MKVS implementation](https://github.com/oasislabs/ekiden/issues/1524)
* [x] [LevelDB for MKVS persistence](https://github.com/oasislabs/ekiden/issues/1529)
* [x] [Expose new MKVS interface on storage nodes](https://github.com/oasislabs/ekiden/issues/1539)
* [x] [Update storage benchmark CLI for MKVS](https://github.com/oasislabs/ekiden/issues/1579)
* [x] [Optimize storage node MKVS implementation](https://github.com/oasislabs/ekiden/issues/1580)
* [x] [Expose new storage interface to runtimes](https://github.com/oasislabs/ekiden/issues/1544)
* [x] [Optimize runtime MKVS implementation](https://github.com/oasislabs/ekiden/issues/1586)
* [x] [cachingclient: Implement caching of MKVS ops](https://github.com/oasislabs/ekiden/issues/1664)
* [x] [More synthetic workloads for benchmarks](https://github.com/oasislabs/runtime-ethereum/issues/658)
* [x] [Replace Parity's storage structures with new Ekiden storage interface](https://github.com/oasislabs/runtime-ethereum/issues/667)
* [x] [Review state maintained by Parity-based runtime](https://github.com/oasislabs/runtime-ethereum/issues/575)
