### ISSUE TITLE
Implement the "final" storage encryption algorithm

### ISSUE THREAD

**Issue by Yawning** [oasisprotocol/oasis-core#1534]
Before it's hard to switch algorithms due to "data people care about being encrypted with it" we need to transition off the HMAC/CTR-AES based SIV construct to something final.

The [CAESAR finalists](https://competitions.cr.yp.to/caesar-submissions.html) were announced last month, and [Deoxys-II](https://competitions.cr.yp.to/round3/deoxysv141.pdf) the first choice use case 3 (defense in depth) would be a good choice.

 * [x] Update the MRAE_Box definition (oasislabs/private-rfcs#99)
 * [x] Correctness first variable time Go implementation.
 * [x] Constant time software Go implementation.
 * [x] Hardware accelerated Go implementation.
 * [x] Add Go implementation to Ekiden (with new MRAE_Box #1546 ).
 * [x] Rust implementation (Can we assume AES-NI? #1545 )
 * [x] JavaScript implementation.
 * [ ] JavaScript "Box" implementation.
