### ISSUE TITLE
Secure key manager runtime

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-core#1550]
Implement the secure key manager runtime proposed in #1548.
 * [x] runtime/common/sgx: Add the `egetkey` crate #1635
 * [x] Persist the RAK for each runtime. #1637
 * [x] Fix/improve the enclave attestation #1641
 * [x] Enclave attestation needs to be secure, and enclave driven #1648
 * [x] implement the actual runtime
