### ISSUE TITLE
Secure key manager

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-core#1551]
Tracking issue for designing and implementing a secure key manager.

## Goal

Fully specify and implement a secure key manager.

## Linked Issues

* [x] [Design a secure key manager](https://github.com/oasislabs/ekiden/issues/1548)
* [x] [Worker host support for the secure key manager](https://github.com/oasislabs/ekiden/issues/1549)
* [x] [Secure key manager runtime](https://github.com/oasislabs/ekiden/issues/1550)
* [x] [Key manager nodes should register with the registry](https://github.com/oasislabs/ekiden/issues/1541)
* [x] [Support per-runtime key managers](https://github.com/oasislabs/ekiden/issues/1556)

Some of these may be obsolete based on the proposed design and should be evaluated (and then closed) when designing the secure key manager:
* [ ] [Key manager should provide non-existence proofs](https://github.com/oasislabs/ekiden/issues/1523)
* [x] [Key manager signatures should be made over a context](https://github.com/oasislabs/ekiden/issues/1522)
* [x] [Dummy KeyManager should use private encryption keys](https://github.com/oasislabs/ekiden/issues/1291)
* [x] [Run Key manager enclave with full interface](https://github.com/oasislabs/ekiden/issues/999)
