### ISSUE TITLE
Merge committee

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-core#1576]
Tracking issue for implementing the merge committee.

## Goal

Fully specify and implement support for merge committees (see [RFC 23](https://github.com/oasislabs/private-rfcs/blob/master/text/0023-storage-design-space.md) for context) which would take over the role of applying updates to storage from the compute committees which would only send logs to the merge committees.

## Linked Issues
* [x] [Design merge committee interfaces](https://github.com/oasislabs/ekiden/issues/1595) - 1w
* [x] [Add Urkel variant that doesn't hash keys](https://github.com/oasislabs/ekiden/issues/1698)
* [x] [Support for merge committee in the committee scheduler](https://github.com/oasislabs/ekiden/issues/1596) - 1w
* [x] [Support for merge committee in BFT roothash](https://github.com/oasislabs/ekiden/issues/1597) - 1w
* [x] [Implement merge committee worker](https://github.com/oasislabs/ekiden/issues/1598)
* [x] [Support for multiple parallel compute committees](https://github.com/oasislabs/ekiden/issues/1775)
* [x] [Support and use ApplyMerge storage operation](https://github.com/oasislabs/ekiden/issues/1823)

Related epics which are superseded by this epic in case this epic is done first:
* [ ] [Merge the TEE and non-TEE runtime instances](https://github.com/oasislabs/runtime-ethereum/issues/550)
