### ISSUE TITLE
Transaction scheduler

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-core#1577]
Tracking issue for implementing the transaction scheduler.

## Goal

Currently, the clients submit all transactions to the leader and the leader schedules them into batches based on arrival order. We should implement a more intelligent transaction scheduler that is able to decide who to submit to based on the content of the transaction.

## Linked Issues

* [x] [Design transaction scheduler interfaces](https://github.com/oasislabs/ekiden/issues/1600) - 1w
* [x] [Node Capabilities support](https://github.com/oasislabs/ekiden/pull/1634)
* [x] [Transaction scheduler nodes register with the registry](https://github.com/oasislabs/ekiden/issues/1626) - 1w
* [x] Clients submit transactions to transaction scheduler committee - 1w
* [x] Transaction scheduler committee produces batches and dispatches to compute committees - 2w
* [x] [Runtimes should expose a CheckTx API](https://github.com/oasislabs/ekiden/issues/1555)
