### ISSUE TITLE
Sentry/proxy node support

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-core#1578]
Implement sentry/proxy node support to mitigate denial of service attacks by not exposing validator/compute nodes directly.

## Linked Issues
* [x] [Initial Tendermint sentry/proxy node support](https://github.com/oasislabs/oasis-core/issues/1828)
* [x] [Simplify sentry node setup](https://github.com/oasislabs/oasis-core/issues/2362)
* [x] [gRPC sentry/proxy node support](https://github.com/oasislabs/oasis-core/issues/1829)
* [ ] [libp2p sentry/proxy node support](https://github.com/oasislabs/oasis-core/issues/1871)

*Estimated cost: 2 sprints*
