### ISSUE TITLE
Write a comprehensive set of auditing tools

### ISSUE THREAD

**Issue by Yawning** [oasisprotocol/oasis-core#1633]
We should have as much automated tooling to monitor the state of our blockchain as possible to detect misbehavior.

* [ ] Audit log for entity, node, runtime registration, and staking.
* [ ] Automated anomaly detection (eg: Something should flip out if invariants are violated, one entity ends up with all the stake, someone is mounting a sybil attack, etc).
* [ ] A sanity checking tool for the genesis block (this should be reusable so that it can be called from both each backend's InitChain *and* various stand-alone tools).

More ideas welcome.  This probably will require spinning up a node that keeps all history, and tracks state changes.  How to best present this information is still an open question (should we have an at-a-glance overview of blockchain health as a webpage a la the [Tor Consensus Health](https://consensus-health.torproject.org/)?)

*Estimated cost: ~2 sprints*
