### ISSUE TITLE
Keymanager: Final steps for policy support

### ISSUE THREAD

**Issue by Yawning** [oasisprotocol/oasis-core#1846]
TODO: split into sub-issues

Things that didn't get done as part of #1824...
 * [x] Write a policy signing tool.
 * [x] Reinitialize the enclave more often (#1812).
 * [x] Figure out how we are going to pass each enclave all of the currently valid MRENCLAVE/MRSIGNER pairs.
 * [x] Figure out how to test/deploy this.
   * [ ] Need a mock MRSIGNER/MRENCLAVE for non-sgx enclave builds.
   * [x] Need test threshold-multisig keys.
   * [ ] Need to change lots of devops.

Lower priority (can be delayed till we stop doing dump/restore on update):
 * [ ] Add key manager policy document submission/validation to the BFT app.
 * [ ] Figure out how the BFT app is supposed to validate policy signatures.
 
*Estimated cost: > 14 days (Realistically, no idea, depends on what the new deployment process looks like.)*

**Comment by Yawning** [comment]
This is basically done, and has been done for a long time.
