### ISSUE TITLE
Node Operator Key Security

### ISSUE THREAD

**Issue by ravenac95** [oasisprotocol/oasis-core#1855]
Epic to track work to achieve: https://github.com/orgs/oasislabs/projects/57#column-5284718

## Goals

Testnet M3 is targeting public participants joining the testnet. We need to be able to support having these participants protect their deployments properly. 

## Linked Issues
* [ ] HSM Support (#1856)
* [ ] Node Identity Key Rotation (#1499)
* [x] go/common/crypto/signature: Abstract out signing into an interface (#1912)
* [x] Use distinct link authentication keys for the worker p2p interface. (#1918)
* [ ] Use distinct link authentication keys for tendermint's p2p interface (blocked on devops deployment changes).
* [x] Refactor the node identity based tendermint PrivateValidator to use `signature.Signer` (#1917)
