### ISSUE TITLE
Support for transaction read/write sets

### ISSUE THREAD

**Issue by peterjgilbert** [oasisprotocol/oasis-core#1919]
Needed in order to support confidential to non-confidential cross-contract/service calls Initially, read/write sets will be specified at per-contract granularity. 

## Details
* [x] [Read/write set encoding and transport](https://github.com/oasislabs/ekiden/issues/2010)
* [ ] [Transaction scheduler should use CheckTx](https://github.com/oasislabs/ekiden/issues/1963)
* [ ] [Support special atomic storage operations on keys](https://github.com/oasislabs/ekiden/issues/1466)
* [ ] [Runtime should verify read/write sets](https://github.com/oasislabs/ekiden/issues/2012)
* [ ] [Read/write set-aware transaction scheduler algorithm](https://github.com/oasislabs/ekiden/issues/2013)
* [ ] [Replicated transaction scheduling and discrepancy detection](https://github.com/oasislabs/ekiden/issues/1656)
* [ ] [Committee scheduler should schedule parallel compute committees](https://github.com/oasislabs/ekiden/issues/2011)

Estimated cost: 13d+
