### ISSUE TITLE
Optimize the storage structures and protocols

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-core#1983]
After the recent changes (e.g., iterators, no more key hashing) and especially after introducing the changed I/O root semantics (#1961) to support merging, we need to go through the storage read syncer protocol and do some optimizations:
* [x] [Make ReadSyncer interface operation-based](https://github.com/oasislabs/ekiden/issues/2048)
* [x] Optimize Merkle proof messages.
* [x] [Support subtree prefetching](https://github.com/oasislabs/ekiden/issues/1716) (e.g., the client can specify prefixes and the server will send it keys matching those prefixes + proofs).
* [x] Optimize node sizes (e.g., `Value` doesn't need a separate `Hash` field, the same goes for the internal leaf node which is always attached to an internal node, etc.).
* [ ] Consider abstracting storage transport so that it is easier to switch the storage interface without changing the runtime protocol. This change should not introduce additional serialization-deserialization steps.

While doing these optimizations care must be taken to not make it easier to mount DoS attacks (also see #1914).
