### ISSUE TITLE
Slashing

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-core#2078]
Slashing should be implemented based on the set of slashing conditions. Ideally there should be E2E tests that verify that slashing functions correctly (e.g., using the byzantine node to invoke incorrect behavior).

### Slashing conditions

* [x] Runtimes / Compute committee
  * [x] Compute/sign/send a wrong result
  * [x] Sign two commitments for the same round but different I/O root/state root/message root.
* [ ] Runtimes / Storage committee
  * [ ] Return a wrong result to read request
  * [ ] Longer-term loss of availability
* [x] Consensus committee
  * [x] [Signing different votes for the same height](https://github.com/oasislabs/oasis-core/issues/1901)

**Comment by kostko** [comment]
All runtime-related slashing conditions (and thresholds to run nodes) should probably be configurable per-runtime.

**Comment by kostko** [comment]
In addition to slashing, misbehaving nodes should also be frozen (similar to how validators are frozen for double signing), with freezing maybe being configurable per runtime (maybe in addition to there being global parameters?).
