### ISSUE TITLE
Implement byzantine nodes

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-core#224]
## Goal

For basic robustness testing of our implementation, it would be nice to have compute nodes which intentionally don't follow the protocol, are laggy when responding, crash, etc.

Then we should be running the testnet with a specific fraction of such byzantine nodes.

## Linked Issues

* [x] [Add controllable crash points into the Ekiden node](https://github.com/oasislabs/ekiden/issues/1601)
* [ ] Missing deadlines / laggy response
* [ ] responding with a different object than the one expected (e.g. a different node)
* [ ] Responding with a different signature than the one expected
    * [ ] copying the commit / reveal of a different committee node
    * [ ] signing but from a random account
