### ISSUE TITLE
Light consensus client/node

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-core#2440]
We should support a light consensus client so that compute nodes which are not validators don't need to sync and execute everything.

Requires #1898 to make it easy to do remote consensus queries after verifying the headers and getting the state roots.

Related to #2349 to avoid compute nodes from doing irrelevant work.

## Linked Issues
* [x] [Basic consensus light client support](https://github.com/oasislabs/oasis-core/pull/2881)
* [x] Tendermint light client provider (part of #2882).
* [x] [Consensus light client interface should expose read-only state](https://github.com/oasisprotocol/oasis-core/issues/3077)
* [x] [go/consensus/tendermint: Refactor internal event handling](https://github.com/oasisprotocol/oasis-core/pull/3091)
* [x] [Make sure TendermintService is only used internally](https://github.com/oasisprotocol/oasis-core/issues/3115)
* [x] [Introduce the notion of consensus backend mode](https://github.com/oasisprotocol/oasis-core/issues/3116)
* [x] [Add non-blocking consensus SubmitTx variant](https://github.com/oasisprotocol/oasis-core/issues/3152)
* [x] [Move `SubmitEvidence` to `LightClientBackend`](https://github.com/oasisprotocol/oasis-core/issues/3169)
* [ ] Light version of the Tendermint consensus backend which uses the light client internally.
