### ISSUE TITLE
go/common/crypto/signature/signer: Implement and use go plugins

### ISSUE THREAD

**Issue by Yawning** [oasisprotocol/oasis-core#3122]
Bloating the repository with a ton of different HSM (etc) signing backends doesn't make sense, and is a maintenance burden. Use the runtime's built-in DLSO support to be able to separate out the non-esssential implementations.

 * [x] Add the plugin signer implementation (#3120)
 * [x]   Move the ledger implementation off into a separate repository (oasisprotocol/oasis-core-ledger#13)
 * [x] Remove the integrated ledger signer implementation (#3128).
 * [x] Remove the ledger oasis-node sub command (#3128).

**Comment by Yawning** [comment]
Ok this is done as far as I am concerned.
