### ISSUE TITLE
Implement ADR 0003

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-core#3431]
The implementation of [ADR 0003](https://github.com/oasisprotocol/oasis-core/blob/master/docs/adr/0003-consensus-runtime-token-transfer.md) is split into the following tasks:
* [x] [Support setting allowance](https://github.com/oasisprotocol/oasis-core/issues/3428)
* [x] [Add runtime accounts](https://github.com/oasisprotocol/oasis-core/issues/3429)
* [x] [Refactor runtime messages](https://github.com/oasisprotocol/oasis-core/issues/3430)
* [x] [Transfer between staking and runtime ledgers](https://github.com/oasisprotocol/oasis-core/issues/2077)
* [ ] [Basic consensus layer state accessors for Rust](https://github.com/oasisprotocol/oasis-core/issues/3564)
