### ISSUE TITLE
oasis-core-runtime: Remove deprecated functionality

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-core#3572]
There is a bunch of functionality present in `oasis-core-runtime` which should be removed in favor of it being moved to runtimes (or the upcoming Runtime SDK) and the `oasis-core-runtime` only providing low-level building blocks:
* [x] `transaction::MethodDispatcher`
  No known external runtime uses it and the only use case for the `MethodDispatcher` is for unit tests.
* [x] `transaction::register_runtime_txn_methods` macro (related to MethodDispatcher).
* [x] `transaction::types::{TxnCall, TxnOutput, TxnCheckResult}` structures (related to MethodDispatcher).
* [x] `storage::StorageContext`
  Instead the storage context reference should be passed inside the `transaction::Context`. If a runtime needs to pass it using thread-local storage, it can implement something like `StorageContext` by itself.
  
  Known users: [oasis-ethwasi-runtime](https://github.com/oasislabs/oasis-ethwasi-runtime), [oasis-ssvm-runtime](https://github.com/second-state/oasis-ssvm-runtime)
* [x] The `runtime`, `tags` and `messages` fields should be removed (together with related methods) from `transaction::Context` in favor of the dispatcher returning tags/messages as part of execution results.
* [x] The `transaction` module in the `oasis-core-client`. This requires moving all E2E test clients to Go.
