### ISSUE TITLE
Tracking issue for state, consensus and storage interface

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-core#94]
RFC: oasislabs/rfcs#1

* [x] Add traits for new consensus and storage interfaces (#95).
* [x] Provide dummy consensus and storage backend implementations which just keep everything in local memory. Implement a test suite for backends which can be reused for other backends. (#106)
* [x] Separate secure channel initialization from regular contract invocation batches (#128).
  * Currently, everything is batched by the compute node, even meta requests which serve for establishing a secure channel between the client and contract. The new protocol requires that there is a computation group instead of just a single compute node which poses a problem for the current design.
* [x] Change the database interface to use the new storage backend (#184).
  * [x] As a first step, it can still store the complete state blob under a single key (but use the new storage interface).
  * [x] Then, we can implement a proper Merklized data structure like the Merkle Patricia Tree (#248).
* [x] Use the new consensus backend in the compute node (#172).
* [ ] Implement proof of publication and atomic delivery. Async contract call infrastructure is already there, we need to define proof of publication (#71).
