### ISSUE TITLE
Database encryption interface

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-core#978]
Tracking issue for database encryption interface (part of [confidentiality core RFC](https://github.com/oasislabs/rfcs/pull/38)).

## Goal
Implement the database encryption interface exposed to the runtime, make it interact with the key manager.

## Linked Issues
- [x] [MRAE AEAD primitive for Rust](https://github.com/oasislabs/ekiden/issues/231) - Already done
- [x] [Database encryption interface](https://github.com/oasislabs/ekiden/issues/686) - Already done
- [x] [Database encryption should use the key manager](https://github.com/oasislabs/ekiden/issues/880) - 7d
- [x] [Database encryption should encrypt keys](https://github.com/oasislabs/ekiden/issues/977) - 1d
- [x] [Change KeyManager get_public_key return value](https://github.com/oasislabs/ekiden/issues/972) - 2d
