### ISSUE TITLE
TEE-enabled runtime execution

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-core#979]
Tracking issue for TEE-enabled runtime execution (part of [confidentiality core RFC](https://github.com/oasislabs/rfcs/pull/38), [rendered version](https://github.com/oasislabs/rfcs/blob/master/text/0009-confidentiality-core.md)).

## Goal
Make it possible for nodes to register as TEE-enabled and attest to the roothash and registry that they have executed the runtime inside a TEE.

## Linked Issues
- [x] [Add AVR parsing and validation](https://github.com/oasislabs/ekiden/pull/923) - Already done
- [x] [Worker should be able to register as an SGX-capable node](https://github.com/oasislabs/ekiden/issues/878) - 4d
- [ ] [Roothash should validate commit attestation for TEE-enabled nodes](https://github.com/oasislabs/ekiden/issues/940) - 4d
- [x] [Write an gRPC->IAS proxy](https://github.com/oasislabs/ekiden/issues/982) - 2d
- [ ] [E2E tests with multiple runtimes](https://github.com/oasislabs/ekiden/issues/1062) - 2d
- [ ] [Should TEE attestations etc be included with commitments in the block header](https://github.com/oasislabs/ekiden/issues/1426) 
- [ ] [sgx: Periodically re-attest with IAS](https://github.com/oasislabs/ekiden/issues/1561)
