### ISSUE TITLE
Single committee throughput optimization

### ISSUE THREAD

**Issue by kostko** [oasisprotocol/oasis-core#998]
Tracking issue for throughput optimization.

## Goal

Increase throughput as reported by the [platform benchmarks](https://github.com/oasislabs/private-ops/tree/master/benchmarking) (both synthetic transfer benchmark and actual playback experiment). This involves multiple components, including ekiden core and runtime-ethereum.

## Linked issues
- [x] [Runtime batch dispatcher should provide start/end-of-batch hooks](https://github.com/oasislabs/ekiden/issues/994) - 0.5d
- [x] [Change DatabaseHandle state commit API](https://github.com/oasislabs/ekiden/issues/997) - 0.5d
- [x] [Mine ethereum block per batch rather than per transaction](https://github.com/oasislabs/runtime-ethereum/issues/207) - 3d
- [x] [Only the leader or backup worker should commit to storage](https://github.com/oasislabs/ekiden/issues/1015) - 1d
- [x] [Measure overhead of using Parity's state trie and consider removing](https://github.com/oasislabs/runtime-ethereum/issues/206) - 5d
