### ISSUE TITLE
Run Key manager enclave with full interface

### ISSUE THREAD

**Issue by willscott** [oasisprotocol/oasis-core#999]
Beyond the changes in #972 , our expectations in the [RFC](https://docs.google.com/document/d/1mHlmI-uaaqIJiM-kmLhZDIUdWIWS4f1LC9EQuE4LOQ8/edit#) for the key manager expect additional functionality than what is currently present.

This issue covers the other work needed for the MVP of the key manager:
* [ ] NewSecureContext - generating new keys for a new enclave
* [ ] GetAuthenticatedKeyPair - Getting a derived key pair from the longterm key for a runtime.
* [ ] Running the key manager in the enclave
* [ ] [Key manager generates its own keys in-enclave](https://github.com/oasislabs/ekiden/issues/1291)
